---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: s3browser-server

spec:
  template:
    spec:
      containers:
        - name: server

          env:
            - name: S3_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-server
                  key: accesskey
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: minio-server
                  key: secretkey

...
